schema: ./src/graphql/schema/schema.graphql
documents: ./src/graphql/**/*.graphql
extensions:
  codegen:
    generates:
      ./src/gql:
        preset: gql-tag-operations-preset
    hooks:
      afterOneFileWrite:
        - prettier --write